### ISSUE TITLE
Storing Searches

### ISSUE THREAD

**Issue by TuOfTimes** [MPCL-McGill/mpclOrch#42]
- Want a way to store searches to specific accounts
- Most likely using Django Sessions and extending the existing User model to store more information

https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html

**Comment by TuOfTimes** [comment]
Implementation:
- Bookmark button on search results, which adds them to a list linked to a profile

**Comment by mlej8** [comment]
For progress, refer to issue #43
