### ISSUE TITLE
Saved Queries Feature Implementation 

### ISSUE THREAD

**Issue by TuOfTimes** [MPCL-McGill/mpclOrch#43]
- Once we can store searches, we want a way to export those searches
- Use the checkout cart as a reference and print the results of the given query

**Comment by Alistair-Russell** [comment]
Frontend of this should be the focus right now. Can you make a basic template and view for the checkout cart front end that just lists all the saved queries? 
For now just create a Query model with two fields: author (string field) and JSON (text field). Then manually make a bunch of them in django admin and create a view that uses all Query objects as it's queryset. 
Then this weekend I will go over how we save these to solr and use them.

**Comment by Alistair-Russell** [comment]
Any progress on this? We should aim to have this functional by mid Feb.

**Comment by Alistair-Russell** [comment]
In order to do this properly you will need to extend the user model and save queries #47 #42

**Comment by mlej8** [comment]
The save query button should only be shown on the result page if a user is logged in.

Added a SavedQueries class in the accounts application.

Extended the user model to take into account the saved features using One-To-Many.

**Comment by mlej8** [comment]
Once saved queries feature is implemented, implement an export button to export all results

**Comment by AlfaBarri15** [comment]
Assign a name for a query in saved queries. Add a name field in query model and show name field of each query in saved_queries.html
